# Generated by Django 3.1 on 2020-08-16 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilizers.city')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Mobilizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('contactnumber', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Learners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('contactnumber', models.CharField(max_length=13)),
                ('age', models.IntegerField(max_length=3)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilizers.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilizers.city')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilizers.course')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilizers.gender')),
                ('mobilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilizers.mobilizer')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilizers.status')),
            ],
        ),
    ]
