# Generated by Django 3.1 on 2020-08-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilizers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mobilizer',
            new_name='Mobilizers',
        ),
        migrations.AlterField(
            model_name='learners',
            name='age',
            field=models.IntegerField(),
        ),
    ]
