# Generated by Django 3.1 on 2020-08-16 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobilizers', '0002_auto_20200816_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilizers',
            name='email',
            field=models.EmailField(default='abc@abc.com', max_length=254),
        ),
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('descreption', models.TextField()),
                ('date', models.DateField()),
                ('mobilizers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilizers.mobilizers')),
            ],
        ),
    ]
